backend:
  # Netlify 사용 시
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"   # 리포지토리 내부 저장 경로
public_folder: "/images/uploads"        # 사이트에서 접근 경로

locale: "ko"

collections:
  # 1) 블로그 글 (Markdown)  ───────────────────────────────────────────
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/posts"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}-{{month}}-{{day}}"
    sortable_fields: ["date", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date",  name: "date",  widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Last Modified", name: "lastMod", widget: "datetime", required: false, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Category", name: "category", widget: "string", required: false, default: "" }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: [] }
      - { label: "Comments enabled", name: "comments", widget: "boolean", default: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Sticky (상단 고정 우선순위)", name: "sticky", widget: "number", default: 0, value_type: "int" }
      - { label: "Body", name: "body", widget: "markdown" }

  # 2) 스펙/정적 페이지 (Markdown)  ────────────────────────────────────
  - name: "spec"
    label: "Specs"
    label_singular: "Spec"
    folder: "src/content/spec"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Comments enabled", name: "comments", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  # 3) 프로젝트 (data 파일; JSON 권장)  ────────────────────────────────
  - name: "projects"
    label: "Projects (data)"
    folder: "src/content/projects"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Link", name: "link", widget: "string", pattern: ["^https?://", "URL은 http(s)여야 합니다."] }

  # 4) 친구/블로그롤 (data 파일; JSON 권장)  ───────────────────────────
  - name: "friends"
    label: "Friends (data)"
    folder: "src/content/friends"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Link", name: "link", widget: "string", pattern: ["^https?://", "URL은 http(s)여야 합니다."] }
